export const ulasan = [
  {
    id: 1,
    nama: "John Doe",
    komentar: "Produk sangat bagus dan pengiriman cepat! Sangat direkomendasikan. Barangnya sesuai dengan deskripsi dan kualitasnya luar biasa.",
    rating: 5,
  },
  {
    id: 2,
    nama: "Jane Smith",
    komentar: "Kualitas produk sesuai dengan deskripsi. Pelayanan juga memuaskan, dan penjual sangat responsif dalam menjawab pertanyaan saya.",
    rating: 4,
  },
  {
    id: 3,
    nama: "Ali Akbar",
    komentar: "Produk oke, tapi pengemasan kurang rapi. Mohon diperbaiki agar pelanggan merasa lebih puas dan nyaman.",
    rating: 3,
  },
  {
    id: 4,
    nama: "Siti Aisyah",
    komentar: "Harga terjangkau dan barang berkualitas. Terima kasih atas pengemasan yang rapi dan pengiriman yang cukup cepat.",
    rating: 4,
  },
  {
    id: 5,
    nama: "Michael Tan",
    komentar: "Sangat puas dengan produk ini. Pengiriman juga cepat dan barang sampai dalam kondisi yang sangat baik.",
    rating: 5,
  },
  {
    id: 6,
    nama: "Dewi Lestari",
    komentar: "Produk tidak sesuai dengan ekspektasi saya. Kualitasnya sangat buruk dan tidak layak digunakan. Saya kecewa karena ini tidak seperti yang dijanjikan.",
    rating: 1,
  },
  {
    id: 7,
    nama: "Rahmat Hidayat",
    komentar: "Pengiriman cukup cepat, tetapi produk memiliki beberapa cacat kecil. Secara keseluruhan masih bisa diterima, tetapi perlu perbaikan kualitas.",
    rating: 3,
  },
  {
    id: 8,
    nama: "Linda Putri",
    komentar: "Barang sangat berkualitas dengan harga yang cukup bersaing. Akan membeli lagi di masa depan karena puas dengan produk ini.",
    rating: 5,
  },
  {
    id: 9,
    nama: "Yusuf Ahmad",
    komentar: "Saya merasa kurang puas dengan produk ini. Warnanya tidak sesuai dengan foto di deskripsi dan kualitasnya biasa saja.",
    rating: 2,
  },
  {
    id: 10,
    nama: "Nina Kartika",
    komentar: "Pelayanan sangat buruk. Saya harus menunggu lebih dari dua minggu untuk menerima pesanan saya. Mohon perbaiki kecepatan pengiriman.",
    rating: 1,
  },
  {
    id: 11,
    nama: "Budi Santoso",
    komentar: "Produk sesuai dengan ekspektasi. Tidak ada masalah selama proses pengiriman, dan barang sampai dalam kondisi baik.",
    rating: 4,
  },
  {
    id: 12,
    nama: "Agus Pratama",
    komentar: "Barangnya bagus, tetapi ukuran sedikit lebih kecil dari yang diharapkan. Semoga bisa lebih akurat ke depannya dalam memberikan deskripsi.",
    rating: 3,
  },
  {
    id: 13,
    nama: "Maria Clara",
    komentar: "Sangat mengecewakan. Barang yang saya terima berbeda dari yang saya pesan. Tidak akan membeli lagi dari toko ini.",
    rating: 1,
  },
  {
    id: 14,
    nama: "Toni Wijaya",
    komentar: "Barang sangat berkualitas. Saya sudah membeli beberapa kali dari toko ini dan selalu puas dengan produk dan pelayanannya.",
    rating: 5,
  },
  {
    id: 15,
    nama: "Rina Andriani",
    komentar: "Pengemasan rapi dan produk sesuai deskripsi. Pengiriman juga lebih cepat dari yang dijanjikan, sangat memuaskan.",
    rating: 4,
  },
  {
    id: 16,
    nama: "Fajar Setiawan",
    komentar: "Produk ini sangat buruk. Setelah satu kali pakai, langsung rusak. Sangat tidak direkomendasikan untuk siapa pun.",
    rating: 1,
  },
  {
    id: 17,
    nama: "Dina Sari",
    komentar: "Barang bagus, tapi kurirnya kurang sopan saat mengantar. Harap diperhatikan agar pengalaman belanja lebih baik.",
    rating: 3,
  },
  {
    id: 18,
    nama: "Hendra Gunawan",
    komentar: "Produk ini sangat bermanfaat untuk kebutuhan saya. Harganya juga terjangkau dan kualitasnya sangat memuaskan.",
    rating: 5,
  },
  {
    id: 19,
    nama: "Susi Wahyuni",
    komentar: "Tidak sesuai dengan deskripsi. Saya merasa tertipu dengan produk ini karena kualitasnya tidak seperti yang diiklankan.",
    rating: 2,
  },
  {
    id: 20,
    nama: "Farid Anwar",
    komentar: "Pelayanan sangat baik. Penjual sangat responsif dan membantu ketika saya memiliki pertanyaan. Sangat direkomendasikan!",
    rating: 5,
  },
  {
    id: 21,
    nama: "Rina Kusuma",
    komentar: "Produk ini cukup baik untuk harga yang ditawarkan. Tidak ada keluhan sejauh ini, dan saya merasa puas.",
    rating: 4,
  },
  {
    id: 22,
    nama: "Adi Putra",
    komentar: "Barang tidak sesuai ekspektasi. Harap lebih memperhatikan kualitas produk agar tidak mengecewakan pelanggan.",
    rating: 2,
  },
  {
    id: 23,
    nama: "Eka Prasetya",
    komentar: "Produk bagus, tapi waktu pengiriman terlalu lama. Harap lebih cepat di masa depan untuk kepuasan pelanggan.",
    rating: 3,
  },
  {
    id: 24,
    nama: "Lina Marlina",
    komentar: "Saya sangat menyukai produk ini! Kualitasnya luar biasa dan sangat tahan lama. Pengiriman juga sangat cepat.",
    rating: 5,
  },
  {
    id: 25,
    nama: "Rizky Ramadhan",
    komentar: "Pengemasan buruk dan barang datang dalam kondisi rusak. Sangat mengecewakan karena tidak sesuai harapan.",
    rating: 1,
  },
  {
    id: 26,
    nama: "Tina Suharto",
    komentar: "Produk ini sangat membantu. Saya sudah merekomendasikannya ke teman-teman saya karena kualitasnya yang sangat baik.",
    rating: 5,
  },
  {
    id: 27,
    nama: "Bagus Saputra",
    komentar: "Harga murah, tapi kualitasnya juga murahan. Harap tingkatkan kualitas agar sesuai dengan deskripsi.",
    rating: 2,
  },
  {
    id: 28,
    nama: "Anita Permata",
    komentar: "Produk sesuai deskripsi dan berfungsi dengan baik. Saya puas dengan pembelian ini dan akan membeli lagi.",
    rating: 4,
  },
  {
    id: 29,
    nama: "Wawan Kurniawan",
    komentar: "Saya sangat kecewa dengan produk ini. Pengemasan buruk dan barang rusak. Mohon lebih berhati-hati.",
    rating: 1,
  },
  {
    id: 30,
    nama: "Nurul Hasanah",
    komentar: "Produk ini sangat memuaskan. Kualitasnya jauh di atas ekspektasi saya. Pengiriman cepat dan rapi.",
    rating: 5,
  },
];
